name: InvisibleItemFrames
version: ${project.version}
main: com.tiffnix.invisibleitemframes.InvisibleItemFrames
api-version: 1.13
description: Adds craftable invisible item frames for survival.
authors:
  - Tiffnix
